# R Matrix Exercises

Through these exercises we will review the matrix data structure and perhaps introduce you to a few ideas for you to discover on your own! Just answer the questions below written in bold:

**Ex 1: Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions is the correct choice.**

In [1]:
A <- c(1,2,3)
B <- c(4,5,6)
rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

**Ex 2: Create a 3 by 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable mat**

In [2]:
mat <- matrix(1:9,byrow=TRUE,nrow = 3)

**Ex 3: Confirm that mat is a matrix using is.matrix()**

In [3]:
is.matrix(mat)

[1] TRUE

**Ex 4: Create a 5 by 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5.**

In [4]:
mat2 <- matrix(1:25,byrow = TRUE,nrow = 5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

**Ex 5: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[7,8]

[12,13]

In [5]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

**Ex 6: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[19,20]

[24,25]

In [6]:
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

**Ex 7: What is the sum of all the elements in mat2?**

In [7]:
sum(mat2)

[1] 325

**Ex 8: Ok time for our last exercise! Find out how to use runif() to create a 4 by 5 matrix consisting of 20 random numbers (4*5=20).**

In [8]:
ranmat <- matrix(runif(20,min=0,max=100),nrow = 4)
ranmat

[,1]      [,2]     [,3]     [,4]     [,5]    
[1,] 76.125035 86.76396 38.09558 46.07675 31.71081
[2,] 65.971231 75.37573 76.22358 42.26843 30.11519
[3,] 39.095067 45.36616 66.77889 12.07960 14.78322
[4,]  0.764645 63.18631 77.60178 76.02879 58.50957

In [9]:
help(runif)